### ISSUE TITLE
Stealing Code is not a good idea kid

### ISSUE THREAD

**Issue by UltimateHackers** [joker25000/Devploit#1]
You have clearly stolen the code from [Recon Dog](https://github.com/UltimateHackers/ReconDog) and its not cool.

**Comment by the-Infected-Drake** [comment]
I agree too, he has clearly stolen the codes. He should have given credits or better should have asked the owner. 😑. Asshole.

**Comment by joker25000** [comment]
I didn't steal any code from brother

**Comment by zD4NI3LH** [comment]
yeah sure m8
