### ISSUE TITLE
 sh: 1: cd: can't cd to //modules

### ISSUE THREAD

**Issue by Aliyan-Haxo** [joker25000/Devploit#2]
Devploit>>>
options no 14>>>>> email collecting
domain name >>>> www.google.com
sh: 1: cd: can't cd to //modules

**Comment by joker25000** [comment]
Run Devploit as root Bro

**Comment by Aliyan-Haxo** [comment]
i solve this problem by copy and pasting modules folder in /root/modules directory close this issue thanks
